Feat: Deduplicate command info
TheOdinProject/odin-bot-v2 pull request #556
Opened 2024-07-01 16:23 UTC by Asartea

## Because
- We duplicate a lot of command info

## This PR
- Deduplicates all duplicated info to a single source of truth
- Updates the snapshots for two commands: both of these purely concern changing whitespace, and I've verified they do not affect the way the command actually looks
- Changes the way two commands declare name their variables to be consistent with the other files and avoid clashing names

## Issue
Closes #553 

## Additional Information
<details>
<summary>Before/After screenshots</summary>
Legacy commands

| Before | After |
| --- | --- |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/011994ce-dff8-44e5-85e5-cf4ede3bbb1c) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/c57ca15e-a0df-4952-afa9-fa286078b51b) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/37de1284-211d-4c9a-b9c3-6d8a62209470) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/afd97756-6215-43ec-9466-1b8f475ecd9f) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/61646cad-f51e-4a57-a7e1-1c3c3b615d0b) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/9e4fae30-e112-4f41-98ad-92d0a018ddf8) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/60d08a18-9b16-495b-abb8-e8ebf41d4e3a) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/02fb7e94-d7f8-4caa-8b01-42150dc390c0) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/525f591a-5430-4e3e-b673-fd51ab144d0c) |
![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/94692c28-4ae8-4f52-8ece-4d70c4fc7d94) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/0c2ee01d-01a2-41d2-a168-b329a2a3ecd9) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/e37f569c-0ef0-4e50-a505-3b2e6086bed0) |

Slash commands

| Before | After |
| --- | --- |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/f166f759-3cdc-4b7a-b742-518e575488c2) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/c4b6c207-b6d9-40d1-8d06-a006db91bd08) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/61c32cf8-61ca-4965-b373-c8b049d56080) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/4494af1a-54bb-4f4b-bb78-2ad45c2db766) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/46c3f2ed-26b3-41cc-886e-c56f70b07f3a) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/1725c0cb-9d18-489b-9eac-5acb1d82a4ad) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/18df9139-cc6f-4ab6-8ce9-12bdd39298c3) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/06294eee-f2ff-4d1a-9aca-c6717f19e559) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/293653af-e0f7-4beb-9384-8dddd5c519a0) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/53ec2edc-8fef-4d80-ad64-7fe041981d4a) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/1a885934-2771-469b-a949-f281588a52d0) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/55796dde-1c86-4d2b-ab86-4466e9b5d375) |
</details>

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
<del>-   [ ] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`</del>
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If this PR adds new features or functionality, I have added new tests
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

2024-07-02 06:06 UTC, 01zulfi requested changes
@Asartea great work, this change as long overdue

left a couple of suggestions below

2024-07-02 06:06 UTC, 01zulfi commented on commandsContent.js
What about moving this file into a new `lib` folder?

2024-07-02 06:06 UTC, 01zulfi commented on commandsContent.js
> +}
Can we move the `color` field to the config file at the root? I say this because we'll need color elsewhere in the codebase as well.

2024-07-02 08:13 UTC, Asartea commented
@01zulfi Done ✅

2024-07-04 14:13 UTC, 01zulfi approved these changes

2024-07-04 14:14 UTC, 01zulfi commented
lgtm 🚀

2024-07-04 14:14 UTC, merged