Feature/command tests
TheOdinProject/odin-bot-v2 pull request #65
Opened 2020-11-19 19:21 UTC by twalton83

- Updated package.json to include script for jest
- created mockBotEngine.test.js (could probably just rename to botEngine.test.js instead?) and added suite to ensure it returns the the desired object
- imported mock function to all other test files

2020-11-19 22:47 UTC, twalton83 commented
@I3uckwheat I merged my changes from my other branch where I refactored the commands to the branch this PR reflect- would you like me to create another PR just for that? It seemed like it would just needlessly create another PR. Both branches are even.

2020-11-20 01:14 UTC, I3uckwheat requested changes

2020-11-20 01:17 UTC, I3uckwheat approved these changes

2020-11-20 01:17 UTC, merged

2020-11-20 01:24 UTC, I3uckwheat commented
> @I3uckwheat I merged my changes from my other branch where I refactored the commands to the branch this PR reflects- would you like me to create another PR just for that refactor? It seemed like it would just needlessly create another PR. Both branches are even.

This was fine :)