shrug, simpleCommands, and time tests
TheOdinProject/odin-bot-v2 pull request #75
Opened 2020-12-05 01:59 UTC by twalton83

- Created snapshots + tests for the `shrug.js`, `simpleCommands.js`, and `time.js` files. 
- The snapshots for shrug are a bit wonky, but I think it's due to escaping characters. I checked the output being returned with a console.log, and it doesn't look the same as the output being returned in the snapshots, even if it does match up properly when run through the bot and manually checked. I'll likely need some review here.
- Additionally, I had to make a few lines dedicated to checking that all of the permutations of the word "shrug" would trigger the regex. I wasn't sure if I needed to do the same in other areas, and am looking to discuss how to improve this piece. checking each one would result in thousands of tests for this one file, so I am not sure if that was necessary if we already checked if the permutations all worked and we only need to know if ONE permutation triggered the regex for sections such as "command should be its own word/group - no leading or trailing characters", or "command can be anywhere in the string".

2020-12-07 20:26 UTC, I3uckwheat requested changes
Looks pretty good other than a few formatting things that should be fixed 👍

2020-12-07 20:26 UTC, I3uckwheat commented on botCommands/shrug.test.js
> +  const permutations = "SHRUG HSRUG RSHUG SRHUG HRSUG RHSUG UHSRG HUSRG SUHRG USHRG HSURG SHURG SRUHG RSUHG USRHG SURHG RUSHG URSHG URHSG RUHSG HURSG UHRSG RHUSG HRUSG GRUSH RGUSH UGRSH GURSH RUGSH U
Stuff like this is just fine for a unit test. The idea is to add stuff as we go. 

the /shrug command is a hard one to test, this all looks fine to me.

2020-12-07 20:26 UTC, I3uckwheat commented on botCommands/shrug.test.js
> +    it.each([
Consider newlines here to make it easier to parse

2020-12-07 20:26 UTC, I3uckwheat commented on botCommands/simpleCommands.test.js
> +  describe('callback', () => {
New line above 106 would help with readability.

2020-12-08 01:21 UTC, twalton83 commented
@I3uckwheat I unintentionally added some other spacing changes I had made to the commit.

2020-12-08 15:06 UTC, I3uckwheat approved these changes

2020-12-08 15:06 UTC, I3uckwheat commented
@twalton83 We'll get it merged then worry about adding eslint and prettier after the fact.

2020-12-08 15:09 UTC, merged

2020-12-08 17:42 UTC, twalton83 commented
@I3uckwheat Thanks!